# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93848c5b5726b8d3960e48f4bfd89126430e00adc63016a35a2e384ab11d76ec11c8943f0a4f2f46bf97b819da91c5149115936394de6544d9e89262d5db4f09

test:
  secret_key_base: 7ad917cc7bdb1e0171478e8355ebd9e7842ec28b248cae69b305372c3dda10d01022b0d1f22a73e8c8e183662b91d825aa65b30b3e479afcc8a8b0e6a9305ae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
